In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.1'

In [4]:
import numpy as ban

In [5]:
ban.__version__

'1.18.1'

In [7]:
ar = np.array(10)
ar

array(10)

In [8]:
ar.shape #to know how many rows and col are there

()

In [9]:
ar.ndim # to find dimesions

0

In [10]:
ar.size ## to find size

1

In [11]:
ar.dtype

dtype('int64')

In [12]:
ar.dtype.name #  to find date type

'int64'

In [13]:
#list
li = [10,20,30,40]
ar = np.array(li)
ar

array([10, 20, 30, 40])

In [14]:
ar.shape

(4,)

In [15]:
np.append(li,50)

array([10, 20, 30, 40, 50])

In [16]:
ar.size

4

In [17]:
ar.ndim

1

In [18]:
ar.dtype

dtype('int64')

In [19]:
ar.dtype.name

'int64'

In [20]:
#tuple
tu = 10,2,0,30,3,4,12,65
ar= np.array(tu)
ar

array([10,  2,  0, 30,  3,  4, 12, 65])

In [21]:
ar.shape # to find rows and columns

(8,)

In [22]:
ar.size  # to find elements in given

8

In [23]:
ar.dtype # to find data type

dtype('int64')

In [24]:
ar.dtype.name

'int64'

In [25]:
#set
se = {10,2,3,6,3}
b = np.array(se)
b

array({3, 10, 2, 6}, dtype=object)

In [26]:
b.dtype

dtype('O')

In [27]:
b.dtype.name

'object'

In [28]:
b.size

1

In [29]:
#dictionary
di = {'key1':'20', 'key2':'30'}
c = np.array(di)
c


array({'key1': '20', 'key2': '30'}, dtype=object)

In [30]:
c.size

1

In [33]:
c.ndim

0

In [34]:
c.dtype


dtype('O')

In [35]:
# N-Dimentional List
nli = [[[[1,2,3],[2,3,4],[3,4,5]]]]
d= np.array(nli)
d

array([[[[1, 2, 3],
         [2, 3, 4],
         [3, 4, 5]]]])

In [36]:
d.shape

(1, 1, 3, 3)

In [37]:
d.size

9

In [38]:
d.ndim

4

In [39]:
#matrix
m = [[1,2,],[2,3]]
e = np.matrix(m)
e

matrix([[1, 2],
        [2, 3]])

In [40]:
e.shape

(2, 2)

In [41]:
import numpy as np
d10=[[[[[[[[[[1,2],[2,3],[4,5]]]]]]]]]]
f = np.array(d10)
f

array([[[[[[[[[[1, 2],
               [2, 3],
               [4, 5]]]]]]]]]])

In [47]:
A = [[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]]
print("A =", A) 
print("A[1] =", A[1])      # 2nd row
print("A[1][2] =", A[1][2])   # 3rd element of 2nd row
print("A[0][-1] =", A[0][-1])   # Last element of 1st Row

A = [[1, 4, 5, 12], [-5, 8, 9, 0], [-6, 7, 11, 19]]
A[1] = [-5, 8, 9, 0]
A[1][2] = 9
A[0][-1] = 0



A = [[1, 4, 5, 12], [-5, 8, 9, 0], [-6, 7, 11, 19]]
A[1] = [-5, 8, 9, 0]
A[1][2] = 9
A[0][-1] = 12


In [1]:
#pratice

In [4]:
import numpy as np
a = np.array([1, 2, 3]) # Create a rank 1 array
#np.rank(a)
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [5]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

(2, 3)
1 2 4


In [6]:
import numpy as np
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"


[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.15117745 0.36569062]
 [0.09449338 0.67235056]]


In [7]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1]) 

2
77


In [10]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"
print(row_r1)
print(row_r2)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)
[5 6 7 8]
[[5 6 7 8]]
