In [1]:
import numpy as np

In [2]:
my_array=np.array([[1,2,3],[2,3,4]],dtype=np.int64)

In [3]:
print(my_array)

[[1 2 3]
 [2 3 4]]


In [4]:
# Create an array of ones
np.ones((3,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
# Create an array of zeros
np.zeros((2,3,4),dtype=np.int16)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int16)

In [6]:
# Create an array with random values
np.random.random((2,2))

array([[0.25134796, 0.72568462],
       [0.78744531, 0.01421691]])

In [7]:
# Create an empty array
np.empty((3,2))


array([[1.86943136e-316, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

In [8]:
# Create a full array
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [13]:
# Create an array of evenly-spaced values
np.arange(10,40,5)

array([10, 15, 20, 25, 30, 35])

In [15]:
# Create an array of evenly-spaced values
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [19]:
# Print the number of `my_array`'s dimensions
print(my_array.ndim)

# Print the number of `my_array`'s elements
print(my_array.size)

# Print information about `my_array`'s memory layout
print(my_array.flags)

# Print the length of one array element in bytes
print(my_array.itemsize)

# Print the total consumed bytes by `my_array`'s elements
print(my_array.nbytes)
# Print the length of `my_array`
print(len(my_array))

# Change the data type of `my_array`
my_array.astype(float)

2
6
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

8
48
2


array([[1., 2., 3.],
       [2., 3., 4.]])

In [21]:
# Initialize `x`
x = np.ones((3,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
# Check shape of `x`
print(x.shape)


(3, 4)


In [23]:
# Initialize `y`
y = np.random.random((3,4))
y

array([[0.99857595, 0.46580562, 0.48130601, 0.53519383],
       [0.92276532, 0.55806501, 0.7025795 , 0.87680303],
       [0.76124635, 0.10676436, 0.45124206, 0.45337369]])

In [24]:
print(y.shape)

(3, 4)


In [25]:
# Add `x` and `y`
x + y

array([[1.99857595, 1.46580562, 1.48130601, 1.53519383],
       [1.92276532, 1.55806501, 1.7025795 , 1.87680303],
       [1.76124635, 1.10676436, 1.45124206, 1.45337369]])

In [29]:
# Import `numpy` as `np`
import numpy as np

# Initialize `x`
x = np.ones((3,4))

# Check shape of `x`
print(x.shape)

x

(3, 4)


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
# Initialize `y`
y = np.arange(4)

# Check shape of `y`
print(y.shape)

# Subtract `x` and `y`
x - y 

(4,)


array([[ 1.,  0., -1., -2.],
       [ 1.,  0., -1., -2.],
       [ 1.,  0., -1., -2.]])

In [28]:
y

array([0, 1, 2, 3])

In [30]:
# Import `numpy` as `np`
import numpy as np

# Initialize `x` and `y`
x = np.ones((3,4))
y = np.random.random((5,1,4))

In [32]:
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
y

array([[[0.77684467, 0.58885975, 0.10606841, 0.02978527]],

       [[0.08871589, 0.81974   , 0.23172605, 0.15643992]],

       [[0.11213742, 0.79692059, 0.85863396, 0.53726226]],

       [[0.76667936, 0.88912886, 0.98440046, 0.90725661]],

       [[0.31370241, 0.14841286, 0.7179492 , 0.33029011]]])

In [31]:

# Add `x` and `y`
x + y

array([[[1.77684467, 1.58885975, 1.10606841, 1.02978527],
        [1.77684467, 1.58885975, 1.10606841, 1.02978527],
        [1.77684467, 1.58885975, 1.10606841, 1.02978527]],

       [[1.08871589, 1.81974   , 1.23172605, 1.15643992],
        [1.08871589, 1.81974   , 1.23172605, 1.15643992],
        [1.08871589, 1.81974   , 1.23172605, 1.15643992]],

       [[1.11213742, 1.79692059, 1.85863396, 1.53726226],
        [1.11213742, 1.79692059, 1.85863396, 1.53726226],
        [1.11213742, 1.79692059, 1.85863396, 1.53726226]],

       [[1.76667936, 1.88912886, 1.98440046, 1.90725661],
        [1.76667936, 1.88912886, 1.98440046, 1.90725661],
        [1.76667936, 1.88912886, 1.98440046, 1.90725661]],

       [[1.31370241, 1.14841286, 1.7179492 , 1.33029011],
        [1.31370241, 1.14841286, 1.7179492 , 1.33029011],
        [1.31370241, 1.14841286, 1.7179492 , 1.33029011]]])

In [38]:
# Select the element at the 1st index
print(my_array[1])


# Select the element at row 1 column 2
#my_2d_array=np.arange([2])
#print(my_2d_array[1][2])

# Select the element at row 1 column 2
#print(my_2d_array[1,2])

# Select the element at row 1, column 2 and 
#print(my_3d_array[1,1,2])

[2 3 4]


In [39]:
# Select items at index 0 and 1
print(my_array[0:2])

# Select items at row 0 and 1, column 1
print(my_2d_array[0:2,1])

# Select items at row 1
# This is the same as saying `my_3d_array[1,:,:]
print(my_3d_array[1,...])

[[1 2 3]
 [2 3 4]]


NameError: name 'my_2d_array' is not defined

In [41]:
a=np.array([1,2,3])
a[start:end] # items start through the end (but the end is not included!)
a[start:]    # items start through the rest of the array
a[:end]      # items from the beginning through the end (but the end is not included!)

NameError: name 'start' is not defined

In [42]:
# Try out a simple example
print(my_array[my_array<2])

# Specify a condition
bigger_than_3 = (my_3d_array >= 3)

# Use the condition to index our 3d array
print(my_3d_array[bigger_than_3])

[1]


NameError: name 'my_3d_array' is not defined

In [44]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[1:7:2]

array([1, 3, 5])

In [45]:
x[0:8:2]

array([0, 2, 4, 6])

In [46]:
x[1:8:3]

array([1, 4, 7])

In [47]:
x[1:8:2]

array([1, 3, 5, 7])

In [48]:
x[0:10:4]

array([0, 4, 8])

In [49]:
 x[-2:10]

array([8, 9])

In [50]:
x[-3:3:-1]

array([7, 6, 5, 4])

In [51]:
 x[5:]

array([5, 6, 7, 8, 9])